config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :interests
  get 'interests/create'

  get 'interests/destroy'

  get 'home/index'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :relationships
  resources :subscriptions
  resources :interests
  resources :events

  root 'home#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :relationships
	has_many :friends, through: :relationships

	has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_relationships, :source => :user

	has_many :subscriptions
	has_many :interests, through: :subscriptions

	validates :name, presence: true
	
	def self.create_with_omniauth(auth)
		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth["uid"]
			user.name = auth["info"]["name"]
		end
	end

	def largeimage
		"http://graph.facebook.com/#{self.uid}/picture?type=large"
	end

	def normalimage
		"http://graph.facebook.com/#{self.uid}/picture?type=normal"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :uid, :provider, :bio, :location)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
 

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">


  <a href="activities.html">Activities</a>
  <a href="interests.html">Interests</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr.</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Tell us about yourself. </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>



<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="w3-card-24 w3-white">
<div>
  <h1>Create Profile</h1>
  <div class="field">
    <%= f.text_field :name, :placeholder => "name" %>
  </div>
    <div class="field">
    <%= f.text_field :location, :placeholder => "hometown" %>
  </div>
  <div class="field">
    <%= f.text_area :bio, :placeholder => 'about me' %>
  </div>

  <div class="actions">
    <%= f.submit :class => "w3-btn w3-teal"%>
  </div>
</div>
</div>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel ="stylesheet" type="text/css" href="../../assets/application.css">

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">

<!-- NEED ROUTING -->
  <a href="activities.html">Activities</a>
  <a href="">Your Profile</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr.</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Connectr. </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>

<div class="w3-card-24 w3-white">

<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
        <th>Location</th>
      <th>Bio</th>
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
          <td><%= user.location %></td>
        <td><%= user.bio %></td>
      
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel ="stylesheet" type="text/css" href="../../assets/application.css">

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">

<!-- NEED ROUTING -->
  <a href="activities.html">Activities</a>
  <a href="">Your Profile</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr.</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Connectr. </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>

<div class="w3-card-24 w3-white">
  <div id="interest-show">

<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p><strong>Interests:</strong>

<%@user.interests.each do |interest|%>
<%= interest.name %>.
<%end%>
</p>

<p><strong>Activities:</strong>

<% @user.interests.each do |interest| %>
  <% interest.events.each do |event| %>
    <%= event.name %>  <br>
  <% end %>
<% end %>
</p>

<p><strong>Friends</strong>
<% @user.relationships.each do |relationship| %>
  <%= relationship.friend.name %> <br>
<% end %>
</p>

<div>
  <%= link_to "Edit Interests", interests_path, class: 'w3-btn w3-teal'%> <br>
</div>

<% if current_user.uid != @user.uid %> 
  <% if current_user.friends.include?(@user) %>
    <%= button_to 'Remove as Friend', {controller: 'relationships', action: 'destroy', id: current_user.relationships.find_by_friend_id(@user)}, :method => :delete %>
  <% else %>
    <%= button_to "Add as Friend", {action: 'create', controller: 'relationships', friend_id: @user.id } %>
  <% end %>
<% end %>