config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :interests
  get 'interests/create'

  get 'interests/destroy'

  get 'home/index'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :relationships
  resources :subscriptions
  resources :interests
  resources :events

  root 'home#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel ="stylesheet" type="text/css" href="../../assets/application.css">

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">

<!-- NEED ROUTING -->
  <a href="activities.html">Activities</a>
  <a href="">Your Profile</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr.</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->
<h1 class="header1"> Connectr. </h1>
</head>
<div class="w3-card-24 w3-white">
<div class="w3-container w3-center w3-animate-opacity">
  
<div class="w3-card-4" style="width:100%">
</div>
</div>

<div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!<br>
    <%= image_tag(current_user.normalimage) %>
    <%= link_to "Sign Out", signout_path, id: "sign_out" %>

<div id="button">
 <%= link_to "Create Profile", edit_user_path(current_user.id), class: 'w3-btn w3-teal'%>
  <%= link_to "Go to Profile", user_path(current_user.id), class: 'w3-btn w3-teal' %>
  </div>
  <% else %>
    <%= link_to "Sign in with Facebook", "auth/facebook", id: "sign_in"  %>
  <% end %>
</div>