config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :interests
  get 'interests/create'

  get 'interests/destroy'

  get 'home/index'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :relationships
  resources :subscriptions
  resources :interests
  resources :events

  root 'home#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :interest
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @interests = Interest.all
  end

  # GET /events/1/edit
  def edit
    @interests = Interest.all
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
 

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">


  <a href="activities.html">Activities</a>
  <a href="interests.html">Interests</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr.</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Tell us about yourself. </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>



<div class="w3-card-24 w3-white">


<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.collection_select :interest_id, @interests, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel ="stylesheet" type="text/css" href="../../assets/application.css">

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">

<!-- NEED ROUTING -->
  <a href="activities.html">Activities</a>
  <a href="">Your Profile</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Events </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>

<div class="w3-card-24 w3-white">
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.location %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>