config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :interests
  get 'interests/create'

  get 'interests/destroy'

  get 'home/index'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :relationships
  resources :subscriptions
  resources :interests
  resources :events

  root 'home#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :subscriptions
	has_many :users, through: :subscriptions
	has_many :events
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:name, :description)
    end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<div class="w3-card-24 w3-white"
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>



        <span class="interests"><h2>Interests</h2></span> 
        
        <h5>Food/Drink</h5> 
        <form>
          <input type="checkbox" name="vehicle1" value="Bike"> Craft Beer
          <input type="checkbox" name="vehicle2" value="Car"> Farm to Fork <br>
          <input type="checkbox" name="vehicle1" value="Bike"> Carolina BBQ
          <input type="checkbox" name="vehicle2" value="Car"> Mixed Drinks
        </form>

        <h5>Athletics</h5> 
        <form>
            <input type="checkbox" name="vehicle1" value="Bike"> Football
            <input type="checkbox" name="vehicle2" value="Car"> Basketball <br>
            <input type="checkbox" name="vehicle1" value="Bike"> Outdoor Activities
            <input type="checkbox" name="vehicle2" value="Car"> Pick Up </form>
        <h5>Arts/Culture</h5>
        <form> 
            <input type="checkbox" name="vehicle1" value="Bike"> Music 
            <input type="checkbox" name="vehicle2" value="Car"> Galleries <br>
            <input type="checkbox" name="vehicle1" value="Bike"> Theater
            <input type="checkbox" name="vehicle2" value="Car">  Museums
        </form>
      </div>

app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel ="stylesheet" type="text/css" href="../../assets/application.css">

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">

<!-- NEED ROUTING -->
  <a href="activities.html">Activities</a>
  <a href="">Your Profile</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Interests </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>

<div class="w3-card-24 w3-white">
<p id="notice"><%= notice %></p>

<h3>Things You Like to Do</h3>

<table>
  <thead>
    <tr>
  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td colspan="3"><%= link_to "#{interest.name}", interest %></td>
       
      <!--   <td><%= link_to 'Show', interest %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- <div>
<%= link_to 'New Interest', new_interest_path %>
</div> -->
</div>

app/views/interests/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- API/STYLESHEETS -->
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel ="stylesheet" type="text/css" href="../../assets/application.css">

    <title>Connectr</title>

    <!-- W3CSS NAVBAR -->
<div class="w3-container w3-center w3-animate-opacity">
<div class="w3-topnav w3-medium w3-black">

<!-- NEED ROUTING -->
  <a href="activities.html">Activities</a>
  <a href="">Your Profile</a>
  <a href="connections.html">Connections</a>
  <a href="signup.html">Sign in</a>

  <!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-hover">
  <button class="w3-btn w3-black"> Connectr. </button>
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #1 -->
      <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">  About this site.  </button>
  <div id="id01" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id01').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Connectr.</h1>
        <h4>Developed in Ruby on Rails, jQuery, and W3CSS.</h4>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #1 END -->

<!-- DROPDOWN MAIN-->
  <div class="w3-dropdown-content w3-border w3-black">

    <!--  DROPDOWN ITEM #2 -->
      <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn"> Developers </button>
  <div id="id02" class="w3-modal">
    <div class="w3-modal-content-black">
      <div class="w3-container">
        <div class="w3-container w3-center w3-animate-opacity">
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn" >×</span>
        <h1>Developed by:</h1>
        <h4>Developed by Nora Orton, Matt Maring, Ben Allred, Heather Shane. </h4>
        <h6>Group 6, get hype</h6>
      </div>
    </div>
  </div>
</div>
  <!-- ITEM #2 END -->


    <!-- DROPDOWN END-->
</div>
</div>
</div>
</div>


<!-- NAVBAR END -->

</head>
<div class="w3-container w3-center w3-animate-opacity">
  <h1 class="header1"> Connectr. </h1>
<div class="w3-card-4" style="width:100%">
</div>
</div>

<div class="w3-card-24 w3-white">
	<div id="interest-show">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @interest.name %>
</p>

<p><strong></strong></p>


<% if current_user.interests.include?(@interest) %>
	<%= button_to 'Unsubscribe', {controller: 'subscriptions', action: 'destroy', id: current_user.subscriptions.find_by_interest_id(@interest)}, :method => :delete %>
<% else %>
	<%= button_to "subscribe", {action: 'create', controller: 'subscriptions', interest_id: params[:id] } %>	
<% end %>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>

</div></div>